# Generated by Django 5.2.16 on 2026-07-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Kan de eigen onboarding-checklist zien'), ('manage_settings', 'Kan de onboarding-instellingen beheren')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_scopes', models.BooleanField(default=True, help_text='Vraag om het koppelen van het character (esi-clones-scope).', verbose_name='Stap: character/ESI koppelen')),
                ('require_discord', models.BooleanField(default=True, help_text='Alleen zichtbaar als de Discord-service is geïnstalleerd.', verbose_name='Stap: Discord koppelen')),
                ('require_home_clone', models.BooleanField(default=True, verbose_name='Stap: home/death-clone op staging')),
                ('require_jump_clones', models.BooleanField(default=True, verbose_name='Stap: jump clones aanwezig')),
                ('staging_name', models.CharField(blank=True, default='', help_text="Bijv. 'BKG-Q2 - Insidious Prime'.", max_length=200, verbose_name='Staging (weergavenaam)')),
                ('staging_system_id', models.PositiveIntegerField(blank=True, help_text='Home/death-clone in dit systeem = afgevinkt (werkt voor NPC-stations).', null=True, verbose_name='Staging solar system id')),
                ('staging_location_id', models.BigIntegerField(blank=True, help_text='Exacte station- of structure-id (citadel). Meest betrouwbaar, ook voor player-structures. Home-clone hier = afgevinkt.', null=True, verbose_name='Staging station/structure id')),
                ('min_jump_clones', models.PositiveSmallIntegerField(default=1, verbose_name='Min. aantal jump clones')),
            ],
            options={
                'verbose_name': 'instellingen',
                'verbose_name_plural': 'instellingen',
                'default_permissions': (),
            },
        ),
    ]
