# Generated by Django 5.2.16 on 2026-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='require_teamspeak',
            field=models.BooleanField(default=True, help_text='Alleen zichtbaar als de TeamSpeak3-service is geïnstalleerd.', verbose_name='Stap: TeamSpeak koppelen'),
        ),
    ]
