# Generated by Django 5.2.16 on 2026-07-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0002_config_require_teamspeak'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hide_when_complete',
            field=models.BooleanField(default=False, help_text="Uit (standaard): de checklist blijft altijd zichtbaar, met een 'voltooid'-melding zodra alles klaar is. Aan: verbergt de widget bij 100%.", verbose_name='Widget verbergen bij 100% voltooid'),
        ),
    ]
