# Generated by Django 5.2.16 on 2026-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0003_config_hide_when_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='staging_name',
            field=models.CharField(blank=True, default='', help_text="Typ een systeem- of structure-naam en laat de id-velden leeg: bij opslaan wordt het id automatisch opgezocht. Systeem = bv. 'SF-XJS'; structure = bv. 'BKG-Q2 - Insidious Prime' (met ' - ').", max_length=200, verbose_name='Staging (naam)'),
        ),
    ]
