# Generated by Django 5.2.16 on 2026-07-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0006_move_staging_to_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpCloneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(verbose_name='Station/structure id')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_clone_locations', to='onboardingchecklist.config')),
            ],
            options={
                'verbose_name': 'jump-clone-locatie',
                'verbose_name_plural': 'jump-clone-locaties',
                'default_permissions': (),
            },
        ),
    ]
