# Generated by Django 5.2.16 on 2026-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0007_jumpclonelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(unique=True, verbose_name='Station/structure id')),
                ('name', models.CharField(blank=True, default='', help_text='Optioneel — wordt automatisch opgezocht waar mogelijk, anders zelf invullen.', max_length=200, verbose_name='Naam')),
            ],
            options={
                'verbose_name': 'locatie in de lijst',
                'verbose_name_plural': 'locaties in de lijst',
                'ordering': ('name',),
                'default_permissions': (),
            },
        ),
    ]
