# Generated by Django 5.2.16 on 2026-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0008_knownlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownlocation',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optioneel emoji vóór de naam, bv. ⚔️ (war), 🏰 (staging), 🏠 (home), ⭐.', max_length=8, verbose_name='Icoon (emoji)'),
        ),
    ]
