# Generated by Django 5.2.16 on 2026-07-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0009_knownlocation_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlocation',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Vóór de naam. Kan zijn: een trefwoord voor een ingebouwd beeld (war = kruis-zwaarden, staging, home, star), een volledige image-URL (https://…/plaatje.png), of een emoji (⚔️).', max_length=300, verbose_name='Icoon'),
        ),
    ]
