# Generated by Django 5.2.16 on 2026-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0010_alter_knownlocation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpclonelocation',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Los per regel: trefwoord (war/staging/home/star), image-URL of emoji.', max_length=300, verbose_name='Icoon'),
        ),
        migrations.AddField(
            model_name='staginglocation',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Los per regel: trefwoord (war/staging/home/star), image-URL of emoji.', max_length=300, verbose_name='Icoon'),
        ),
    ]
