# Generated by Django 5.2.16 on 2026-07-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0011_jumpclonelocation_icon_staginglocation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpclonelocation',
            name='icon_size',
            field=models.PositiveSmallIntegerField(default=26, verbose_name='Icoon-grootte (px)'),
        ),
        migrations.AddField(
            model_name='staginglocation',
            name='icon_size',
            field=models.PositiveSmallIntegerField(default=26, verbose_name='Icoon-grootte (px)'),
        ),
    ]
