# Generated by Django 5.2.17 on 2026-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0012_jumpclonelocation_icon_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='require_linkcheck',
            field=models.BooleanField(default=False, help_text='Extra stap die de Link Check-plugin (aa-linkcheck) bevraagt: staan alle daar verplicht gestelde koppelingen, en is er geen ingetrokken token? Onder de stap komt een regel voor elk character dat er nog niet is. Doet niets als die plugin niet geïnstalleerd is.', verbose_name='Stap: Link Character Check'),
        ),
    ]
