# Generated by Django 5.2.17 on 2026-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0012_jumpclonelocation_icon_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='include_alts',
            field=models.BooleanField(default=False, help_text='Uit (standaard): alleen de main telt. Aan: elk character van het account moet aan de ESI- en clone-stappen voldoen; per character komt er een regel onder de stap te staan.', verbose_name='Alts meetellen'),
        ),
    ]
