# Generated by Django 5.2.17 on 2026-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingchecklist', '0013_config_include_alts'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='alts_home_clone',
            field=models.BooleanField(default=False, help_text='Uit (standaard): alleen de main hoeft zijn death clone op een staging-locatie te hebben, ook als alts meetellen — een alt parkeer je nu eenmaal ergens anders. Aan: elk character.', verbose_name='Death clone ook voor alts'),
        ),
        migrations.AddField(
            model_name='config',
            name='alts_jump_clones',
            field=models.BooleanField(default=False, help_text='Uit (standaard): alleen de main. Aan: elk character moet aan de jump-clone-eis voldoen.', verbose_name='Jump clones ook voor alts'),
        ),
    ]
